DROP TABLE IF EXISTS books;

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  img TEXT NOT NULL,
  rating_out_of_five TEXT NOT NULL,
  title TEXT NOT NULL,
  price TEXT NOT NULL,
  in_stock BOOLEAN NOT NULL
);